#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my_database
#    username: root
#    password: Q172737wer!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        ddl-auto: create
#        default_batch_fetch_size: 1000
#server:
#  port: 8080
#  error:
#    include-exception: false
#    include-stacktrace: never
#    whitelabel:
#      enabled: false
#api:
#  service:
#    key: "MMHCbkSwOcSiJn%252FzrSRDE6THXM0uauq7G8DnD1ysBvoQOGtb8F%252BBKIeLlsjG%252BJcp5Ik6OzCvcP7XSrE8iZ%252Bjtw%253D%253D"
#
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true
#  api-docs:
#    path: /v3/api-docs
#    enabled: true
#  show-actuator: true
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  paths-to-match:
#    - /**



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: "root"
    password: "Q172737wer!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
