name: Make application.yml

on:
  pull_request:
    branches:
      - develop

jobs:
  create-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          # 기본 설정 파일
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          
          # 테스트용 설정 파일
          mkdir -p ./src/test/resources
          cat << EOF > ./src/test/resources/application-test.yml
          spring:
            datasource:
              url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
              driver-class-name: org.h2.Driver
              username: sa
              password: 
            jpa:
              hibernate:
                ddl-auto: create-drop
              show-sql: true
              properties:
                hibernate:
                  format_sql: true
                  dialect: org.hibernate.dialect.H2Dialect
            h2:
              console:
                enabled: true
                path: /h2-console
            sql:
              init:
                mode: always
                platform: h2
          
          logging:
            level:
              org.hibernate.SQL: debug
              org.hibernate.type: trace
              org.springframework.test: debug
          EOF
        shell: bash
      
      - name: Build and Test
        run: ./gradlew test --info -Dspring.profiles.active=test
