name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make application.yml  # application.yml 파일 생성
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          echo "=== Checking if application.yml was created ==="
          ls -la src/main/resources/
          echo "=== Checking application.yml content ==="
          cat src/main/resources/application.yml
        shell: bash

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Generate QueryDSL Q classes
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean compileJava

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: everguide-test
          path: build/libs/*.jar
